Map<dynamic, dynamic> listaDadosTeste1 = {
  'nome': 'M4 Sherman',
  'tipo': 'Carro de combate Médio',
  'paisOrigem': 'EUA',
};

List<Map<dynamic, dynamic>> listaDadosTeste2 = [
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
  {'nome': 'M4 Sherman', 'paisOrigem': 'EUA', 'tipo': 'Carro de combate Médio'},
];

Map<dynamic, dynamic> dadosDetalhesTeste1 = {
  'id': '0',
  'imagem': '[Imagem]',
  'nome': 'M4 Sherman',
  'paisOrigem': 'EUA',
  'tipo': 'Carro de combate médio',
  'fabricante': 'American Locomotive Company',
  'utilizadores': 'EUA',
  'quantidadeProduzida': '49,234',
  'peridoServico': '1942–1957',
  'massa': '30.3 Toneladas',
  'comprimento': '5.84 m',
  'altura': '2.74 m',
  'largura': '2.62 m',
  'tripulacao': '5',
  'custoUnitario': '44.556 dólares',
  'armamento': 'Canhão 75 mm gun M3 e metralhadora .50 Browning M2HB',
};
